"""Cross-language compatibility tests: fixtures below were generated by the
retired Node backend (scryptSync / aes-256-gcm in src/password.js, src/crypto.js)
so existing password hashes and encrypted provider tokens must round-trip."""

import pytest

from app.services import crypto

# node crypto.scryptSync("correct horse battery", salt, 64)
NODE_SCRYPT = (
    "a1b2c3d4e5f60718293a4b5c6d7e8f90:"
    "fa42cf51e33cec0f189baf0b10fc6acd1b00b84120aaeb7bb9b1be63d6757c4c"
    "160f0eba0b09afd77f7485cfba9690f46587c07699d741432403760da5519129"
)

# node aes-256-gcm of "ghp_super_secret_token_123" with key sha256("shared-secret-key")
NODE_AES = "IvVf1CLRiYXA7WPA.7_M11vVHnhBx7A9-18mADg.BFSsV6-4kNge0tJCHhYjVehk_irUxcT61Ts"


def test_node_scrypt_hash_verifies():
    assert crypto.verify_password("correct horse battery", NODE_SCRYPT)
    assert not crypto.verify_password("wrong password", NODE_SCRYPT)


def test_password_roundtrip_matches_node_format():
    stored = crypto.hash_password("s3cure-password")
    salt, _, digest = stored.partition(":")
    assert len(salt) == 32 and len(digest) == 128
    assert crypto.verify_password("s3cure-password", stored)
    assert not crypto.verify_password("s3cure-password!", stored)


def test_verify_password_rejects_malformed():
    assert not crypto.verify_password("anything", "")
    assert not crypto.verify_password("anything", "no-colon")
    assert not crypto.verify_password("anything", "salt:not-hex")


def test_node_aes_ciphertext_decrypts(monkeypatch):
    from app import config

    monkeypatch.setattr(
        config.get_settings(), "credential_encryption_key", "shared-secret-key"
    )
    crypto._key.cache_clear()
    try:
        assert crypto.decrypt_secret(NODE_AES) == "ghp_super_secret_token_123"
        roundtrip = crypto.encrypt_secret("another token")
        assert crypto.decrypt_secret(roundtrip) == "another token"
        assert "=" not in roundtrip
        assert len(roundtrip.split(".")) == 3
    finally:
        crypto._key.cache_clear()


def test_tampered_ciphertext_rejected(monkeypatch):
    from app import config

    monkeypatch.setattr(
        config.get_settings(), "credential_encryption_key", "shared-secret-key"
    )
    crypto._key.cache_clear()
    try:
        tampered = NODE_AES[:-2] + ("aa" if not NODE_AES.endswith("aa") else "bb")
        with pytest.raises(Exception):
            crypto.decrypt_secret(tampered)
    finally:
        crypto._key.cache_clear()
